### ISSUE TITLE
Solver does not implement signal handling

### ISSUE THREAD

**Issue by daajoe** [Rubydrag0n/sudokusat-example#1]
Your solver does not implement signal handling to the started process tree. This results in the situation that the sat solver (clasp) might still be running even though the benchmark tool or cluster scheduler sent a kill signal to the solver after timeout.
(check with kill -15 mysolver or kill -9  and make sure that also the started processes are terminated then)

**Comment by AntonReinhard** [comment]
What exactly do you mean? When I execute my program and kill it while it's using clasp by pressing Ctrl+C it usually kills the sat-solver first and then my program finishes very quickly. Is that different when the program is killed by the benchmark tool?

**Comment by daajoe** [comment]
Create a simple script to run instead of clasp such as
```
#!/usr/bin/env python

while True:
  print('foobar')

```
Then, replace your syscall with
`syscall << "python foo.py ";
//syscall << solver;                                                                                      
//syscall << " " << cnf_filename << " > " << solution_filename;
`

and run 
`./Sudoku solve ../../instances/private/225/table15-4.normal.txt clasp
`

then kill the process Sudoku with
`killall -15 Sudoku`

This will kill the Sudoku process. However, the python script will continue running, which is not intended as you should also properly terminate the subprocesses you started.

(Since your solver is quite fast and the solver terminates then anyways after a couple of seconds it just does not occur. Anyhow, if sudokus get bigger we get into problems there.)

**Comment by AntonReinhard** [comment]
Signal handling should be fixed with the newest commit.
